# Generated by Django 3.0 on 2019-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('unique_squirrel_id', models.IntegerField()),
                ('shift', models.CharField(choices=[('AM', 'am'), ('PM', 'pm')], max_length=2)),
                ('date', models.DateTimeField()),
                ('age', models.CharField(max_length=8)),
                ('primary_fur_color', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=12)),
                ('specific_location', models.CharField(max_length=100)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(max_length=100)),
                ('kuks', models.BooleanField()),
                ('quass', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
            ],
        ),
    ]
