# Generated by Django 3.0 on 2019-12-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191204_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='quass',
            new_name='quaas',
        ),
    ]
