# Generated by Django 3.0 on 2019-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(null=True),
        ),
    ]
